### ISSUE TITLE
Precision fails when using negative ignored index

### ISSUE THREAD

**Issue by mfoglio** [Lightning-AI/metrics#1040]
## 🐛 Bug

When setting `ignore_index=-1` accuracy can be computed, but precision fails with the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.12/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 18, in <module>
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.9/site-packages/torchmetrics/metric.py", line 248, in forward
    self.update(*args, **kwargs)
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.9/site-packages/torchmetrics/metric.py", line 312, in wrapped_func
    update(*args, **kwargs)
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.9/site-packages/torchmetrics/classification/stat_scores.py", line 185, in update
    tp, fp, tn, fn = _stat_scores_update(
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.9/site-packages/torchmetrics/functional/classification/stat_scores.py", line 154, in _stat_scores_update
    preds, target, _ = _input_format_classification(
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 432, in _input_format_classification
    target = to_onehot(target, max(2, num_classes))  # type: ignore
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.9/site-packages/torchmetrics/utilities/data.py", line 99, in to_onehot
    return tensor_onehot.scatter_(1, index, 1.0)
RuntimeError: index -1 is out of bounds for dimension 1 with size 2
```

I also tried to use a positive number, say `1000` and I get an error for Accuracy too:
```
ValueError: The highest label in `target` should be smaller than the size of the `C` dimension of `preds`.
```

### To Reproduce

```py
import torch
import torchmetrics


print('torch', torch.__version__) #  1.11.0+cu102
print('torchmetrics', torchmetrics.__version__) # 0.8.1

accuracy = torchmetrics.Accuracy(ignore_index=-1)
precision = torchmetrics.Precision(ignore_index=-1)

preds = torch.Tensor([
    [0.2, 0.3],
    [0.8, 0.7],
])
target = torch.IntTensor([-1, 0])

print('accuracy', accuracy(preds, target))  #  tensor(1.)
print('precision', precision(preds, target))  # error (see above)
```

### Expected behavior

Precision ignores the index `-1`.

### Environment

- TorchMetrics version 0.8.1
- Python & PyTorch Version (e.g., 1.0): 1.11.0+cu102

**Comment by mfoglio** [comment]
If the error above is really a bug and you can to point to the proper place where the ignored labels should be handled, I'll be happy to work on a fix.

**Comment by SkafteNicki** [comment]
Hi @mfoglio,
We are fully aware of this issue that our classification metrics does not out of the box support negative index. We will make this part of a greater refactor of the classification package (this issue #1001) in the upcoming weeks.

**Comment by SkafteNicki** [comment]
Issue will be fixed by classification refactor: see this issue https://github.com/Lightning-AI/metrics/issues/1001 and this PR https://github.com/Lightning-AI/metrics/pull/1195 for all changes

Small recap: This issue ask for support that ignore_index can be outside the [0, num_classes] range for precision metric. After the refactor, all new classification metrics support this. Here is an example for precision:
```python
from torchmetrics.functional import binary_precision
import torch

preds = torch.tensor([0.2, 0.7, 0.6, 0.3])
target = torch.tensor([1, 1, 0, 0, -1])

binary_precision(preds_prob, target_prob, ignore_index=-1)  # tensor(0.5000)
```
Issue will be closed when https://github.com/Lightning-AI/metrics/pull/1195 is merged.

**Comment by mfoglio** [comment]
Fantastic! Thank you!
