### ISSUE TITLE
import error: cannot import name 'PILLOW_VERSION' from 'PIL'

### ISSUE THREAD

**Issue by quancs** [Lightning-AI/metrics#1142]
## 🐛 Bug

When import `torchmetrics` in python, it reports the error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchmetrics\__init__.py", line 53, in <module>
    from torchmetrics.image import (  # noqa: E402
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchmetrics\image\__init__.py", line 31, in <module>
    from torchmetrics.image.lpip import LearnedPerceptualImagePatchSimilarity  # noqa: F401
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchmetrics\image\lpip.py", line 25, in <module>
    from lpips import LPIPS as _LPIPS
  File "D:\ProgramData\Miniconda3\lib\site-packages\lpips\__init__.py", line 11, in <module>
    from lpips.lpips import *
  File "D:\ProgramData\Miniconda3\lib\site-packages\lpips\lpips.py", line 9, in <module>
    from . import pretrained_networks as pn
  File "D:\ProgramData\Miniconda3\lib\site-packages\lpips\pretrained_networks.py", line 3, in <module>
    from torchvision import models as tv
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchvision\__init__.py", line 2, in <module>
    from torchvision import datasets
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchvision\datasets\__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchvision\datasets\fakedata.py", line 3, in <module>
    from .. import transforms
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchvision\transforms\__init__.py", line 1, in <module>
    from .transforms import *
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchvision\transforms\transforms.py", line 17, in <module>
    from . import functional as F
  File "D:\ProgramData\Miniconda3\lib\site-packages\torchvision\transforms\functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (D:\ProgramData\Miniconda3\lib\site-packages\PIL\__init__.py)
```

### To Reproduce

Install torchmetrics[audio]:
```
pip install torchmetrics[audio]
```

Import it in python:
```python
import torchmetrics
```

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 0.9.2
- Python & PyTorch Version (e.g., 1.0): Python 3.8.5, PyTorch 1.10.0
- Any other relevant information such as OS (e.g., Linux): Win 10

**Comment by SkafteNicki** [comment]
Actual problem comes from `torchvision` and not `torchmetrics`:
https://github.com/pytorch/vision/issues/1718
Either:
* Update torchvision to a newer version where it should have been fixed
* Install a version of pillow that is compatible: `conda install pillow=6.2.1`
