### ISSUE TITLE
MS-SSIM crashes for different sized images

### ISSUE THREAD

**Issue by Queuecumber** [Lightning-AI/metrics#1224]
## 🐛 Bug

My validation set has images of many different sizes. Currently the MS-SSIM module seems to cache all of these images and then computing only at the end of validation. That's probably not a good idea for a couple of reasons. 

1. It makes the code crash when the images have different sizes which I think is a pretty common situation. 
2. Some of the images could be quite large so caching them is a good way to run out of memory

I think most people would compute SSIM over each image in the batch and sum the results over all batches and divide by the total number of images. Why isn't that being done here? Or did I miss an option for it?

### To Reproduce

1. Take two images of different sizes
2. Call update on them separately
3. Call compute

#### Code sample

```
import torch
from torchmetrics import StructuralSimilarityIndexMeasure

ssim = StructuralSimilarityIndexMeasure()

a = torch.rand(5, 3, 10, 10)
b = torch.rand(5, 3, 20, 20)

ssim.update(a, a)
ssim.update(b, b)

print(ssim.compute())
```

output: 

```
Traceback (most recent call last):
  File "repro.py", line 12, in <module>
    print(ssim.compute())
  File "/mnt/fsx-outputs-chipdesign/mehrlich/poetry_cache/metabit-wl5Ts0fA-py3.8/lib/python3.8/site-packages/torchmetrics/metric.py", line 531, in wrapped_func
    value = compute(*args, **kwargs)
  File "/mnt/fsx-outputs-chipdesign/mehrlich/poetry_cache/metabit-wl5Ts0fA-py3.8/lib/python3.8/site-packages/torchmetrics/image/ssim.py", line 117, in compute
    preds = dim_zero_cat(self.preds)
  File "/mnt/fsx-outputs-chipdesign/mehrlich/poetry_cache/metabit-wl5Ts0fA-py3.8/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 42, in dim_zero_cat
    return torch.cat(x, dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 10 but got size 20 for tensor number 1 in the list.
```

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): git master, installed with pip
- Python & PyTorch Version (e.g., 1.0): 3.8/1.12
- Any other relevant information such as OS (e.g., Linux):

**Comment by Queuecumber** [comment]
I can't even find any discussion about this using git blame because the ssim files have been moved around so many times

Anyway I have a fixed implementation of this that I will open a PR with. It looks like many of your image metrics suffer from this problem, so if you want I can probably fix them all for you.

**Comment by SkafteNicki** [comment]
@Queuecumber thanks for raising this issue.
I am aware that many of our metrics are probably not optimal in some cases. We always welcome contributions to making our metrics faster or more memory efficient.

**Comment by Queuecumber** [comment]
I have a prototype for SSIM, probably will have something complete for a draft PR early next week

**Comment by Queuecumber** [comment]
I'm curious if you have any testimonials from people who are using the image metrics in production code 

With the current implementation I don't see how it's possible outside of some very specific circumstances

**Comment by Queuecumber** [comment]
That's definitively possible, I'm still scoping out what exactly is required for the other metrics

**Comment by SkafteNicki** [comment]
Cool, lets take one metric at the time. If we can make due with only saving some intermediate state that would be wonderful as long as the tests are still passing for correctness.

**Comment by Queuecumber** [comment]
BTW it looks like the "none" reduction is broken for MS-SSIM. If you pass anything larger than a batch size of 1 it crashes because the shapes of things aren't correct.

not sure what you want to do about that

**Comment by Queuecumber** [comment]
Is there any particular objection to depending on pytorch-mssim instead of reimplementing this? 

The current implementation seems to be very broken, pytorch-mssim supports everything that it needs and it is known to be correct, and reinventing this code seems like it's just inviting bugs for no reason.

**Comment by Borda** [comment]
> Is there any particular objection to depending on pytorch-mssim instead of reimplementing this?

I would say that having our own implementation would be perfect; we just need to be careful of not copy their code for eventual licencing issues

**Comment by Queuecumber** [comment]
Yes I was able to get a correct implementation of both without needing the extra dependency

**Comment by Borda** [comment]
@Queuecumber, can we look forward to some more contributions? :rabbit:

**Comment by Queuecumber** [comment]
Yes, CVPR deadline tomorrow after that I should have more time to work on the rest of these
