### ISSUE TITLE
Crash when using .clone on MetricCollection with MatthewsCorrCoef

### ISSUE THREAD

**Issue by arroqc** [Lightning-AI/metrics#1292]
## 🐛 Bug

When building a MetricCollection with MatthewsCorrCoef as part of the list, the use of .clone method raises an error.
This happens only in 0.10.0. The same code in 0.9.3 will work.

### To Reproduce

1. Install torchmetrics 0.10.0
2. Use code sample below

This will lead to the following issue when .clone tries to deepcopy:
```
>>> metrics.clone(prefix='train')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./anaconda3/envs/pytorch/lib/python3.8/site-packages/torchmetrics/collections.py", line 300, in clone
    mc = deepcopy(self)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "./anaconda3/envs/pytorch/lib/python3.8/copy.py", line 264, in _reconstruct
    y = func(*args)
  File "./anaconda3/envs/pytorch/lib/python3.8/copyreg.py", line 91, in __newobj__
    return cls.__new__(cls, *args)
TypeError: __new__() missing 1 required positional argument: 'num_classes'
```

#### Code sample
```
import torchmetrics
metrics = torchmetrics.MetricCollection([torchmetrics.MatthewsCorrCoef(num_classes=2, threshold=0.5)])
metrics.clone(prefix='train')
```

### Expected behavior

Clone doesn't crash :)

### Environment

pip install torchmetrics==0.10.0
- Python & PyTorch Version (e.g., 1.0): Python 3.8. torch 1.12.1
- Any other relevant information such as OS (e.g., Linux): Tested on local mac and inside linux docker

**Comment by SkafteNicki** [comment]
Hi @arroqc, this is a similar issue to https://github.com/Lightning-AI/metrics/issues/1274, which has been resolved in https://github.com/Lightning-AI/metrics/pull/1250 after https://github.com/Lightning-AI/metrics/issues/1249. Please update to version `v0.10.1` that was released 5 days ago (https://github.com/Lightning-AI/metrics/releases/tag/v0.10.1)
