### ISSUE TITLE
Dice score cannot be calculated for each class separately

### ISSUE THREAD

**Issue by asbjrnmunk** [Lightning-AI/metrics#1601]
Dice score cannot be calculated without reduction. The documentation states 

> average:
>             Defines the reduction that is applied. Should be one of the following:
>             - ``'micro'`` [default]: Calculate the metric globally, across all samples and classes.
>             - ``'macro'``: Calculate the metric for each class separately, and average the
>               metrics across classes (with equal weights for each class).
>             - ``'weighted'``: Calculate the metric for each class separately, and average the
>               metrics across classes, weighting each class by its support (``tp + fn``).
>             - ``'none'`` or ``None``: Calculate the metric for each class separately, and return
>               the metric for every class.
>             - ``'samples'``: Calculate the metric for each sample, and average the metrics
>               across samples (with equal weights for each sample).

while neither `'none'` nor `None` works.

 Minimal reproducing example:

```
>> import torch
>> from torchmetrics import Dice
>> Dice(average='none', num_classes=3)
```
raises the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[redacted]/site-packages/torchmetrics/classification/dice.py", line 168, in __init__
    raise ValueError(f"The `reduce` {average} is not valid.")
ValueError: The `reduce` none is not valid.
```
Same error is encountered with `average=None`. 
Library versions tried: 0.11.0, 0.11.3. Python version 3.10.6.

Looking at the code, something seems fishy. Comparing the following two code snippets of `classification/dice.py`:
https://github.com/Lightning-AI/metrics/blob/825d17f32ee0b9a2a8024c89d4a09863d7eb45c3/src/torchmetrics/classification/dice.py#L149-L151
and
https://github.com/Lightning-AI/metrics/blob/21b23b6d472ec542c764a789af63bd054fbb3512/src/torchmetrics/classification/dice.py#L167-L168

It seems line 167 is wrong since `average` is not modified between the two snippes.

**Comment by asbjrnmunk** [comment]
Clossing to reopen with correct format.
